eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
      host: 192.168.80.132
      port: 5672
      password: admin
      username: admin